apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cadence

resources:
  - ../base
  - ingress.yaml

images:
  - name: cadence-backend
    newTag: dev
  - name: cadence-client
    newTag: dev

patches:
  - target:
      kind: Deployment
      name: cadence
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Deployment
      name: cadence-client
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Job
      name: cadence-migrate
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
