apiVersion: v1
kind: Secret
metadata:
    name: cadence-credentials
    namespace: cadence
type: Opaque
stringData:
    DB_USER: ENC[AES256_GCM,data:rRGDlaNezw==,iv:Cs5cVWcx3vEnMdWLlIacEumKG5CxxCfgbBibdbGBV7Q=,tag:BcYjrafb80OoCPN9gLM06w==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:NxqKHvf4rzriRe0=,iv:JbWKOemrIy2j3JSeh7X4B1e1xar60mk29NBbANx8qjk=,tag:mIa1EgVCy54l3D7B76xjGw==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:nZgMG/MOhzQKHQQ=,iv:7wxv/F//W3LcSR1bzhzJjPafOJxQzqC6cKpnzTTsV7Y=,tag:0+kisFO/8cXOgGp4k4XZyg==,type:str]
sops:
    age:
        - recipient: age1s9fqc3qeh7qxkdnarj5jrcn4tjehjukp9p30n28phe8205mnvpzqc47z8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNFl6VUlmK0Z3bnN5NGpN
            WlkvNGJVZFVYeHhqREd0VzRabDlYak0xYmkwCmdOVmFiZFZ6MXcrUEp0UHk4OEh2
            V0c0ZitFZ3MzU0gyaWYrT25pS3V1VDgKLS0tIGowZFpiZWJWNmpjZS9NaUpaa0l3
            czIvV3NnTVZmNml5TGZ0bVZTcXNHdWcK69p9IWW1CVkqS4aWQLsAwV0Vd3W5iN5+
            0QBo3tLpQIhrchE18q6d+ueIv+8wCioxPAir1enuxCgHO4bF6rWCsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-21T21:39:38Z"
    mac: ENC[AES256_GCM,data:W09Eb8I3RdGt/7IbupVOtIXhhlhTldu6N/3Ij5pvVHmEMwDFq3pvNAc/x0wk0uvu5ww+W7pt4n3RmorxeKLKw1Dd1XtCFfRxeIt1jDz7j8Hvh8sCZZJz4np8Kd6wL2dDNzGYpcYChl6ggdGO+Sraclg1Jz+mdFLKOa2HXLI5VXw=,iv:eaqQUMA20Ei+Fkvd7RUTf4QfiujCbN52qRQpEcWiGVE=,tag:FwwOZaXc80n888eVjuPWGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
