apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cadence
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: default
    traefik.ingress.kubernetes.io/router.middlewares: cadence-ratelimit@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: app.cadence.nightnoryu.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: cadence
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cadence-client
                port:
                  number: 80
  tls:
    - hosts:
        - app.cadence.nightnoryu.com
