apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cadence

resources:
  - ../base
  - ingress.yaml

images:
  - name: ghcr.io/nightnoryu/cadence-backend
    newTag: 0.1.0
  - name: ghcr.io/nightnoryu/cadence-client
    newTag: 0.1.0
