apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cadence

resources:
  - ../base
  - ingress.yaml

generators:
  - secret-generator.yaml

images:
  - name: ghcr.io/cadence-muse/cadence
    newTag: 0.1.1
  - name: ghcr.io/cadence-muse/client
    newTag: 0.1.2
