apiVersion: v1
kind: Secret
metadata:
    name: cadence-credentials
    namespace: cadence
type: Opaque
stringData:
    DB_USER: ENC[AES256_GCM,data:/DqP00esVw==,iv:Pu2sCRQaeq99SrUmx7K2/keF618O6DGR8k2cYs+Wlac=,tag:UwYsGEswPoP7hDJohq4yOw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:dTJZFEJZ26VgJu/EnLsnlg==,iv:spsHXhcDs4HwFAp79As1mfsMMzE/lx5orkAV3WvlGic=,tag:3ObUi4SbyYbbi/tW/MhKCA==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:gfbiZZfdTrxjiFj4IN9d/A==,iv:pCmwcaTrTUUJOmrWD+7B7/nXMQQ/V/ycbU3/f3ySaOA=,tag:cq/mnujM4qwxaZWzUA9xmw==,type:str]
sops:
    age:
        - recipient: age1s9fqc3qeh7qxkdnarj5jrcn4tjehjukp9p30n28phe8205mnvpzqc47z8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTWNCNEVOeW9qR2dqdUtu
            VEMxUjIvY1BibkRQV09IeUdYbklUN0FrWnpFCkVTYWVaWDhBTERzdStqZCtBMTZ2
            STBZUm1FVDNMcGZUODlHUEJRaFhDSTgKLS0tIFhTeGpqL1JFMnBNdnYvUW9QOVd0
            cjdTVDRrZnRuWHovS1ptR0JlUVlpSFUKfxzAwQ6iVP6r3rTy7volI9W0u8g1x89y
            eZnOBNlQPVdKCRw06Tpeho8C3dq4iXe7jLC0tCyD65CN1+2GlocrPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T09:42:16Z"
    mac: ENC[AES256_GCM,data:zpujZJd/UjVIWXF9HGvdgnQsH+revLcKWok6twkREatg7IC9TXcLgnaCbzZKftZUDyOfiiUQVgPKm7h03nee4ASC4NkFfKxpBv3UkBHHSbXC88MC9brso7Vr8Iu7A4B8V7N2rLkUc/RX00c4cVUf1U0aQvUyJdh28ntzWE4dUyQ=,iv:vbDYaBz9vEFKQY96r4DYB3cJWQC1Psda1zr2BF7HM50=,tag:4JV5ZUupqYuGPwLvBNuWog==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
