apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

resources:
  - namespace.yaml
  - loki
  - promtail
  - grafana

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: cadence-logging
