apiVersion: v1
kind: Secret
metadata:
    name: grafana-credentials
    namespace: logging
type: Opaque
stringData:
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:EOQUMko=,iv:Dh1NxVcbJ5pfyGO2lXTfN//FcVG70jcynYer5UjqEkk=,tag:S4y6Vi5cmjg+uCpGMEVubQ==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:ZdNIKzSppVHEXbrIZKtLFA==,iv:CfUEKDSW7k5vPkeYXsHFKpsLuIJAMNRejzjkgwwAtGo=,tag:9avUSk84HkWaCsNnlxwDBQ==,type:str]
sops:
    age:
        - recipient: age1s9fqc3qeh7qxkdnarj5jrcn4tjehjukp9p30n28phe8205mnvpzqc47z8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWmR3QVpGS3haM21hTWZM
            REVHQlpVK04vbFFQYk1ZNjFlWGVCT0V5TGhnCkhjVUtGNm1KSk1sNHNxR0FpUTZZ
            Y0QrbW9WYW1nbFJ1elR6bFRKa0xmNXMKLS0tIFBycS9JVk1od1ZsRlNkRUVqeU1M
            RmpUU3R1blA3OHpCY3hFdFROMGdDQmsKsalOqHezBP5jR0Xjbgmui7A3oXWgZwWH
            oJqrZXWPkYuS9ttbZIwBqlLWBrEbuFZkKEaQ7kJhoZBbeZeNy60fAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-20T15:35:42Z"
    mac: ENC[AES256_GCM,data:8oX3rvBUSghynCTaCDNbly9CHn7LwAgtfwVxhPWG3ZUVB4n9lITpxPorlFjsDanW6c9yiNYSF587T9v3kVdQoifRmWmy8zjfhChC8AYu0MetJmIZx45Q69YDY0nqrPSe6BdFaH9BRXZqVKaiFfAFl/n/swqasLh7mDRBzSDDZSk=,iv:q6oeUHT5EJTHqpgKkJzXlcw+NpLgVGP7yQDX+iwyUdQ=,tag:GMcbkm66zL2Kt9GMRSNayQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
