apiVersion: v1
kind: Secret
metadata:
    name: cadence-credentials
    namespace: cadence-staging
type: Opaque
stringData:
    DB_USER: ENC[AES256_GCM,data:xudyIzhNww==,iv:e74PYj9aRZRZuOhUIE1Hqd5zun+nYwFAzlzpcip3L+g=,tag:9xwJ/5pgvc/069/mPO/NAQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:2hqDImyY+m2mjNkW,iv:reluOsXpCIBw4NkydFoeMnDbOk5LYcEJ/WHE+d9r+fI=,tag:BL2yWFLd619yWsCXygApAA==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:t3QpRbZOIAJDdto4,iv:nv9G+o6kXxcxeA2/0uJO7dJLiAeDhltsWrAewSwRoEA=,tag:2D93TOEUXS6o3vbV/fZ6aQ==,type:str]
sops:
    age:
        - recipient: age1s9fqc3qeh7qxkdnarj5jrcn4tjehjukp9p30n28phe8205mnvpzqc47z8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIb2ZzSmtwUTFTdTBqVG1L
            cXYvZHFTYXhxVCsydVhqSzJHVFdzakxGbGxRCnlHREJ2NGVIdVNsSHBHdDl1a3BL
            Y0lSWUVIVVhxZWZZcFUxZndQUjU4czgKLS0tIGI2cE9wRUhsSjNVVFR5UXJXRDlz
            T2p5TFVyMU1wU3JleDFYTThVT3ZZRVEKfzlbFl1YWr0PdTcvoZtIazNKJR4kl3gL
            96gT0Y1ShWEUiQyK3yjhIwpkpWrex4X/saCG7Q8qZvEA/cOtIHwZlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T13:35:51Z"
    mac: ENC[AES256_GCM,data:tuTZp+ItT4XX0hlBZO+RkwG2U3zqFDvMh6xN9RlutFQv5EWuVG4VPSSQqJUpUDO/5uwzYlOoiYRmyXzaCdy7iEIZG8G6xNAdbGcyVoqDNY3KVUu1PIrL8hd0TALwoH0EsMKNXSTvqhJsVwG9o9t9Q75xDUX4cSCt4CWrG4dfkrw=,iv:mgzjd5uJA4rxfhE8fG6hga3OBDbriL19BACA7VGA7yA=,tag:WogTU56zc6ZeXvsHRcYWvw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
