apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cadence

resources:
  - ../base
  - ingress.yaml

images:
  - name: ghcr.io/nightnoryu/cadence-backend
    newTag: latest
  - name: ghcr.io/nightnoryu/cadence-client
    newTag: latest

replicas:
  - name: cadence
    count: 2

patches:
  - target:
      kind: ConfigMap
      name: cadence-config
    patch: |-
      - op: add
        path: /data/CORS_ALLOWED_ORIGINS
        value: https://cadence.app
