apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cadence

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - redis-pvc.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - cadence-deployment.yaml
  - cadence-service.yaml
  - cadence-client-deployment.yaml
  - cadence-client-service.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: cadence
