apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cadence

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres
  - redis
  - cadence-server
  - cadence-client

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: cadence
